language: go

go:
  - 1.7.x
  - 1.8.x

install:
  # tools
  - make tools

  # project
  - make dependencies
  - make install

script:
  # build all test imports
  - go test -i ./...

  - make lint

  # test and do code coverage
  - ginkgo -r -cover -race -skipPackage="testdata"
  - gover
  - if [ "$TRAVIS_SECURE_ENV_VARS" = "true" ] && [[ $(go version) =~ go1\.5 ]]; then goveralls -coverprofile=gover.coverprofile -service=travis-ci -repotoken $COVERALLS_TOKEN; fi

env:
  # coveralls.io
  secure: "CPuDl59GuLvd8BFbJwuy2mynpN4e9l2LAPF42yaf8b9HQIYQPrSeycqQAIDPQgKhk4x3/FbX1JrvieTP/P2hx+alxJv6tvEvh/aGg91h/dgLpUHiIvBQfa7viUKZrxkER3pQg30Ql2fMJOz8gKPWyB0mNvm5Eh4ysdjJmILTGuM="

sudo: false
